title:              "COMMA"
tagline:            "NEXT COMMA NEW THING"
email:              "hvv01829@gmail.com"
description:        "블로그 설명"
author:             "Gujuhyun"
baseurl:            "/"
url:                "https://ofcomma.com"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"



# Social Profiles
#twitter_username:   twitter_username
instagram_username: instagram_of_comma
facebook_username:  facebook_username
#linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
